# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 003ced30110b8865539e61d914e5fba6fcc3467e86cbfb7a5eac33332cbaa7fe5cc7a82e956389e45de28e75595ba75a48b09404bca565211996e946a3ee4a49

test:
  secret_key_base: 95c75b3a653bedb8ef0c67259450e836e373fbf13c6f34e0b21609b5b16ce0d777898f8efc9d5359211244cfa1ea6a9f0854817fd5edc888e43c31927136017c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
